const nodemailer = require("nodemailer");
console.log("SMTP LOGIN:", process.env.BREVO_SMTP_LOGIN);
console.log("SMTP PASSWORD:", process.env.BREVO_SMTP_PASSWORD ? "Loaded" : "Missing");
console.log("EMAIL FROM:", process.env.EMAIL_FROM);

const transporter = nodemailer.createTransport({
  host: "smtp-relay.brevo.com",
  port: 587,
  secure: false,
  auth: {
    user: process.env.BREVO_SMTP_LOGIN,
    pass: process.env.BREVO_SMTP_PASSWORD,
  },
});

async function sendEmail(to, subject, text) {
  return transporter.sendMail({
    from: `"${process.env.EMAIL_FROM_NAME}" <${process.env.EMAIL_FROM}>`,
    to,
    subject,
    text,
  });
}

const twilio = require("twilio");

const twilioClient = twilio(
  process.env.TWILIO_ACCOUNT_SID,
  process.env.TWILIO_AUTH_TOKEN
);

async function sendSMS(phone, message) {
  return twilioClient.messages.create({
    body: message,
    from: process.env.TWILIO_PHONE_NUMBER,
    to: phone,
  });
}

async function makeVoiceCall(phone, message) {

  return twilioClient.calls.create({

    twiml: `
<Response>
    <Say voice="alice">
        ${message}
    </Say>
</Response>
    `,

    from: process.env.TWILIO_PHONE_NUMBER,
    to: phone

  });

}

const { generateNotificationContent } = require("./aiService");
const db = require("../database/database");

// Fixed disclaimer appended ONLY to the generated email body. It is never
// added to the SMS or the voice call script.
const EMAIL_AI_FOOTER = `
-------------------------------------------------
Automated Communication Notice
This notification was automatically generated by the RecallAI Communication Agent using the official vehicle recall bulletin together with verified customer vehicle records. The content has been generated to accurately reflect the recall information available at the time of notification.
-------------------------------------------------
`;

// Writes a single row to notification_logs. Every successful send (Email,
// SMS, Voice Call) gets its own row, and Send Again never overwrites a
// previous row — it just adds a new one.
function logNotification(recallId, customerId, channel, status) {

  return new Promise((resolve) => {

    db.run(
      `
      INSERT INTO notification_logs
      (recall_id, customer_id, channel, status)
      VALUES (?, ?, ?, ?)
      `,
      [recallId, customerId, channel, status],
      (err) => {

        if (err) {
          console.error("Failed to write notification log:", err);
        }

        resolve();

      }
    );

  });

}

// Generates the Email Subject/Body, SMS, and Voice Call content via AI ONCE,
// then dispatches every channel concurrently with Promise.all() instead of
// sequentially. Each successful send writes its own notification_logs row.
async function notifyCustomer(customer, recall) {

  const aiNotification = await generateNotificationContent(recall, customer);

  const emailSubject = aiNotification.email_subject;
  const emailBody = `${aiNotification.email_body}\n${EMAIL_AI_FOOTER}`;

  const recallId = recall.id;
  const customerId = customer.customer_id;

  const tasks = [];

  if (customer.notification === "Email") {

    tasks.push(
      sendEmail(customer.email, emailSubject, emailBody).then(() =>
        logNotification(recallId, customerId, "Email", "Sent")
      )
    );

  } else if (customer.notification === "SMS + Email") {

    tasks.push(
      sendEmail(customer.email, emailSubject, emailBody).then(() =>
        logNotification(recallId, customerId, "Email", "Sent")
      )
    );

    tasks.push(
      sendSMS(customer.phone, aiNotification.sms).then(() =>
        logNotification(recallId, customerId, "SMS", "Sent")
      )
    );

  } else if (customer.notification === "Voice Call + SMS") {

    tasks.push(
      sendSMS(customer.phone, aiNotification.sms).then(() =>
        logNotification(recallId, customerId, "SMS", "Sent")
      )
    );

    tasks.push(
      makeVoiceCall(customer.phone, aiNotification.voice_call).then(() =>
        logNotification(recallId, customerId, "Voice Call", "Completed")
      )
    );

  }

  await Promise.all(tasks);

  return aiNotification;

}

module.exports = {
  sendEmail,
  sendSMS,
  makeVoiceCall,
  notifyCustomer,
};